### ISSUE TITLE
eventhandlers in metrichandler are not disposed

### ISSUE THREAD

**Issue by rmul** [catwithboots/Tessup#1]
we attach eventhandlers but never detach or dispose of them
![image](https://cloud.githubusercontent.com/assets/5443466/6025005/9b17aeec-abcf-11e4-952b-162cab2cd49e.png)

**Comment by rmul** [comment]
When do you think you will have fixed this, we are waiting for a solution!

**Comment by Toppertje** [comment]
dude, this looks awesome, but that damned bug! Please go fix!Asap

**Comment by cihatgenc** [comment]
Fixed

**Comment by rmul** [comment]
Hij heeft niks gedaan die gast, dus niet opgelost
